import test from 'node:test';
import assert from 'node:assert/strict';
import { openDb,seed,now } from '../src/db.js';
import { recordService,appointmentCoding,reviewServiceCode,serviceGaps,sourceLineIssues,noteServiceMentions } from '../src/appointment-coding.js';
import { documentationChecks,checkout } from '../src/billing.js';
function setup(t){const db=openDb(':memory:');seed(db);t.after(()=>db.close());const doctor=db.prepare("SELECT * FROM users WHERE id='doctor-001'").get(),biller=db.prepare("SELECT * FROM users WHERE id='biller-001'").get(),patient=db.prepare("SELECT * FROM users WHERE id='portal-001'").get();db.prepare("UPDATE encounters SET date_of_service='2026-10-09' WHERE id='enc-001'").run();for(const kind of ['ASSESSMENT','PLAN'])db.prepare('INSERT INTO clinical_sections VALUES (?,?,?,?,?,?)').run(kind,'enc-001',kind,'Fictional documented services and source only',doctor.id,now());return {db,doctor,biller,patient,enc:()=>db.prepare("SELECT * FROM encounters WHERE id='enc-001'").get(),sign(){db.prepare("UPDATE encounters SET status='SIGNED',signed_at=? WHERE id='enc-001'").run(now())}}}
const service={source_section_id:'PLAN',category:'MEDICATION',state:'PERFORMED_IN_HOUSE',description:'Fictional triamcinolone administration',indication:'Fictional documented indication only',drug:'triamcinolone acetonide',dose:'10 mg',route:'Fictional test route',performance_reference:'Fictional administration report',search_terms:'triamcinolone',reviewed:true};
const review={procedure_system:'HCPCS',procedure_code:'J3301',diagnosis_code:'M54.50',modifier:'',units:1,rationale:'Fictional source and descriptor reviewed; not a clinical recommendation',reviewed:true};
test('service facts derive from a scoped source note, remain immutable and revisions preserve history',t=>{const f=setup(t);assert.throws(()=>recordService(f.db,f.biller,'enc-001',service),/Assigned clinician/);assert.throws(()=>recordService(f.db,f.doctor,'enc-001',{...service,source_section_id:'foreign'}),/source note/);const first=recordService(f.db,f.doctor,'enc-001',service);assert.equal(recordService(f.db,f.doctor,'enc-001',service).id,first.id);const second=recordService(f.db,f.doctor,'enc-001',{...service,state:'CANCELED',supersedes_id:first.id});assert.equal(appointmentCoding(f.db,f.doctor,'enc-001').services[0].id,second.id);assert.throws(()=>recordService(f.db,f.doctor,'enc-001',{...service,supersedes_id:first.id}),/stale/);assert.equal(f.db.prepare('SELECT count(*) n FROM encounter_services').get().n,2);assert.throws(()=>f.db.exec("UPDATE encounter_services SET state='PERFORMED_IN_HOUSE'"),/immutable/);assert.throws(()=>f.db.exec('DELETE FROM encounter_services'),/immutable/);f.sign();assert.throws(()=>recordService(f.db,f.doctor,'enc-001',service),/before signing/)});
test('ordered, discussed, canceled and external services never become in-house billing lines',t=>{for(const state of ['ORDERED','DISCUSSED','CANCELED','PERFORMED_ELSEWHERE']){const f=setup(t),s=recordService(f.db,f.doctor,'enc-001',{...service,state});f.sign();assert.equal(appointmentCoding(f.db,f.biller,'enc-001').services[0].billing_review_allowed,false);assert.throws(()=>reviewServiceCode(f.db,f.biller,'enc-001',{...review,service_id:s.id}),e=>e.status===422)}});
test('imaging and medication missing facts require clarification; unavailable CPT never generates fabricated candidates',t=>{const f=setup(t);const ct=recordService(f.db,f.doctor,'enc-001',{...service,category:'CT',description:'CT requested',body_part:'lumbar spine',laterality:'Not applicable',contrast:'UNKNOWN',search_terms:'computed tomography'});const d=appointmentCoding(f.db,f.biller,'enc-001').services[0];assert(d.gaps.includes('Contrast protocol'));assert.equal(d.catalog_available,false);assert.equal(d.catalog_candidates.length,0);f.sign();assert.throws(()=>reviewServiceCode(f.db,f.biller,'enc-001',{...review,service_id:ct.id}),/completed details/);assert(serviceGaps({category:'XRAY',state:'PERFORMED_IN_HOUSE',details:{description:'X-ray',body_part:'knee',laterality:'left',indication:'documented',performance_reference:'report'}}).includes('Number of X-ray views'));assert(serviceGaps({category:'MEDICATION',state:'PERFORMED_IN_HOUSE',details:{}}).includes('Administered dose and measurement unit'))});
test('human-reviewed candidates become matching claim lines with durable source provenance and independent coverage',t=>{const f=setup(t),s=recordService(f.db,f.doctor,'enc-001',service);assert(appointmentCoding(f.db,f.biller,'enc-001').services[0].catalog_candidates.some(c=>c.code==='J3301'));assert.throws(()=>reviewServiceCode(f.db,f.biller,'enc-001',{...review,service_id:s.id}),/Sign/);f.sign();assert.throws(()=>reviewServiceCode(f.db,f.biller,'enc-001',{...review,service_id:s.id,reviewed:false}),/confirmation/);assert.throws(()=>reviewServiceCode(f.db,f.biller,'enc-001',{...review,service_id:s.id,procedure_code:'INVALID'}),/catalog/);const r=reviewServiceCode(f.db,f.biller,'enc-001',{...review,service_id:s.id}),line={...r.line,charge_cents:1000};assert.deepEqual(sourceLineIssues(f.db,f.enc(),line),[]);assert(sourceLineIssues(f.db,f.enc(),{...line,units:2}).length);assert(sourceLineIssues(f.db,f.enc(),{...line,source_review_id:undefined}).length);const claim=checkout(f.db,f.doctor,'enc-001',[line]);assert.equal(claim.status,'AWAITING_CONNECTOR');assert.equal(f.db.prepare('SELECT review_id FROM claim_line_sources').get().review_id,r.id);assert.equal(JSON.parse(f.db.prepare('SELECT snapshot FROM claim_outbox').get().snapshot).lines[0].source_review_id,r.id);assert.throws(()=>f.db.exec("UPDATE service_code_reviews SET rationale='changed'"),/immutable/)});
test('duplicate source codes, stale revisions and cross-organization/encounter source links are rejected',t=>{const f=setup(t),s=recordService(f.db,f.doctor,'enc-001',service);f.sign();const a=reviewServiceCode(f.db,f.doctor,'enc-001',{...review,service_id:s.id}),b=reviewServiceCode(f.db,f.biller,'enc-001',{...review,service_id:s.id});assert(documentationChecks(f.db,f.enc(),[{...a.line,charge_cents:1},{...b.line,charge_cents:1}]).some(x=>x.includes('billed twice')));f.db.prepare("INSERT INTO encounters (id,org_id,patient_id,clinician_id,date_of_service,status,signed_at) VALUES ('other','demo-clinic','patient-001','doctor-001','2026-10-09','SIGNED','now')").run();const e=f.db.prepare("SELECT * FROM encounters WHERE id='other'").get();assert(sourceLineIssues(f.db,e,a.line).some(x=>x.includes('cross-encounter')));assert.throws(()=>appointmentCoding(f.db,f.patient,'enc-001'),/Practice coding staff/);f.db.prepare("INSERT INTO organizations VALUES ('other','Other')").run();f.db.prepare("INSERT INTO users (id,org_id,email,name,role,password_hash) VALUES ('other','other','other@test','Other','BILLER','x')").run();assert.throws(()=>appointmentCoding(f.db,{id:'other',org_id:'other'},'enc-001'),/Encounter not found/);f.db.prepare("UPDATE users SET active=0 WHERE id='biller-001'").run();assert.throws(()=>reviewServiceCode(f.db,f.biller,'enc-001',{...review,service_id:s.id}),/Practice coding staff/)});

test('note mentions preserve exact source offsets without inferring negation, intent, performance or billing',()=>{const content='No CT scan needed. Discussed X-ray. MRI performed elsewhere. Injection canceled.';const mentions=noteServiceMentions([{id:'note',kind:'PLAN',content}]);assert.deepEqual(mentions.map(m=>m.category),['CT','XRAY','MRI','INJECTION']);for(const m of mentions){assert.equal(content.slice(m.start_offset,m.end_offset),m.matched_phrase);assert.equal(m.source_section_id,'note');assert.equal(m.status,'MENTION_ONLY');assert.equal(m.procedure_code,undefined)}assert.equal(noteServiceMentions([{id:'normal',kind:'PLAN',content:'Continue existing care; no services named.'}]).length,0)});
