import test from 'node:test';
import assert from 'node:assert/strict';
import { openDb, seed, now } from '../src/db.js';
import { checkout, documentationChecks } from '../src/billing.js';

function setup(){const db=openDb(':memory:');seed(db);const user=db.prepare("SELECT * FROM users WHERE role='PHYSICIAN'").get();const enc=db.prepare("SELECT * FROM encounters WHERE id='enc-001'").get();return {db,user,enc};}
const line={procedure_system:'CPT',procedure_code:'99213',diagnosis_code:'M54.50',units:1,charge_cents:15000}; // Test-only specimen, not a clinical recommendation.
test('checkout blocks unsigned or undocumented encounters',()=>{const {db,user,enc}=setup();assert.match(documentationChecks(db,enc,[line]).join(' '),/signed/);assert.throws(()=>checkout(db,user,enc.id,[line]),e=>e.status===422);assert.equal(db.prepare('SELECT count(*) n FROM claims').get().n,0);db.close()});
test('validated checkout atomically creates one queued claim; second checkout blocked',()=>{const {db,user,enc}=setup();for(const kind of ['ASSESSMENT','PLAN'])db.prepare('INSERT INTO clinical_sections VALUES (?,?,?,?,?,?)').run(kind,enc.id,kind,'Test documentation',user.id,now());db.prepare("UPDATE encounters SET status='SIGNED', signed_at=? WHERE id=?").run(now(),enc.id);const claim=checkout(db,user,enc.id,[line]);assert.equal(claim.status,'AWAITING_CONNECTOR');assert.equal(claim.total_cents,15000);assert.equal(db.prepare('SELECT status FROM encounters WHERE id=?').get(enc.id).status,'CHECKED_OUT');assert.throws(()=>checkout(db,user,enc.id,[line]),e=>e.status===409);db.close()});
test('authorization mismatches block checkout',()=>{const {db,user,enc}=setup();for(const kind of ['ASSESSMENT','PLAN'])db.prepare('INSERT INTO clinical_sections VALUES (?,?,?,?,?,?)').run(kind,enc.id,kind,'Test',user.id,now());db.prepare("UPDATE encounters SET status='SIGNED',signed_at=? WHERE id=?").run(now(),enc.id);db.prepare('INSERT INTO authorizations (id,org_id,patient_id,payer_name,procedure_code,status) VALUES (?,?,?,?,?,?)').run('auth','demo-clinic','patient-001','Example Health Plan','12345','APPROVED');assert.match(documentationChecks(db,{...enc,signed_at:now()},[{...line,authorization_id:'auth'}]).join(' '),/Authorization/);db.close()});
