import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openDb,seed } from '../src/db.js';
import { searchCodes,coverageView,recordCoverage,importLicensedCodes } from '../src/code-coverage.js';
function fixture(t){const dir=mkdtempSync(join(tmpdir(),'coverage-test-')),path=join(dir,'db');let db=openDb(path);seed(db);db.prepare('UPDATE encounters SET date_of_service=? WHERE id=?').run('2026-10-09','enc-001');t.after(()=>{db.close();rmSync(dir,{recursive:true,force:true})});return {get db(){return db},restart(){db.close();db=openDb(path)},biller:{id:'biller-001',org_id:'demo-clinic'},doctor:{id:'doctor-001',org_id:'demo-clinic'},patient:{id:'portal-001',org_id:'demo-clinic'}}}
const context={encounter_id:'enc-001',plan_reference:'Fictional group A PPO',procedure_system:'HCPCS',procedure_code:'J3301',diagnosis_code:'M54.50',modifier:'',units:1,place_of_service:'11'};
const evidence={reviewed:true,source_kind:'INSURER_PORTAL',source_reference:'Fictional fixture, not insurer data',status:'COVERED_SUBJECT_TO_TERMS',checked_on:'2026-10-09',expires_on:'2026-10-10',eligibility:'ACTIVE',network:'IN_NETWORK',provider_enrollment:'STAFF_REVIEWED',requirements:'Fictional conditional benefit; clinician review required',cost_sharing:'Unknown'};
test('real public catalogs use release dates, official descriptions, search and unavailable-date behavior',t=>{const f=fixture(t);const hc=searchCodes(f.db,f.biller,{q:'J3301',service_date:'2026-10-09'});assert.match(hc.results[0].description,/triamcinolone/);assert.equal(hc.source.count,7448);assert.equal(searchCodes(f.db,f.doctor,{system:'ICD10CM',q:'M5450',service_date:'2026-10-09'}).results[0].code,'M54.50');assert.equal(searchCodes(f.db,f.biller,{service_date:'2027-01-01'}).available,false);assert.equal(searchCodes(f.db,f.biller,{system:'ICD10CM',service_date:'2027-09-30'}).available,true);assert.equal(searchCodes(f.db,f.biller,{system:'ICD10CM',service_date:'2027-10-01'}).available,false);assert.throws(()=>searchCodes(f.db,f.biller,{service_date:'2026-02-30'}),/valid date/);assert.throws(()=>searchCodes(f.db,f.patient,{service_date:'2026-10-09'}),/Access denied/)});
test('coverage defaults unknown and immutable member-context evidence survives restart with audits',t=>{const f=fixture(t);assert.equal(coverageView(f.db,f.biller,context).status,'NOT_VERIFIED');recordCoverage(f.db,f.biller,{...context,evidence});f.restart();const v=coverageView(f.db,f.biller,context);assert.equal(v.status,'COVERED_SUBJECT_TO_TERMS');assert.equal(v.authenticated_insurer_response,false);assert.match(v.procedure.description,/triamcinolone/);assert.equal(v.diagnosis.description,'Low back pain, unspecified');assert.throws(()=>f.db.prepare("UPDATE coverage_reviews SET member_id='x'").run(),/immutable/);assert.throws(()=>f.db.prepare('DELETE FROM coverage_reviews').run(),/immutable/);assert.equal(f.db.prepare("SELECT count(*) n FROM audit_log WHERE action='RECORD_COVERAGE_REVIEW'").get().n,1)});
test('coverage never transfers across plan, code, diagnosis, modifier, units, POS, provider, member or organization',t=>{const f=fixture(t);recordCoverage(f.db,f.biller,{...context,evidence});for(const changed of [{plan_reference:'Other plan'},{procedure_code:'J1100'},{diagnosis_code:'M54.2'},{modifier:'25'},{units:2},{place_of_service:'22'}])assert.equal(coverageView(f.db,f.biller,{...context,...changed}).status,'NOT_VERIFIED');f.db.prepare("UPDATE encounters SET clinician_id='biller-001' WHERE id='enc-001'").run();assert.equal(coverageView(f.db,f.biller,context).status,'NOT_VERIFIED');f.db.prepare("UPDATE encounters SET clinician_id='doctor-001' WHERE id='enc-001'").run();f.db.prepare("UPDATE patients SET member_id='new-member' WHERE id='patient-001'").run();assert.equal(coverageView(f.db,f.biller,context).status,'NOT_VERIFIED');f.db.prepare("UPDATE patients SET member_id='DEMO-MEMBER-001',payer_name='Other insurer' WHERE id='patient-001'").run();assert.equal(coverageView(f.db,f.biller,context).status,'NOT_VERIFIED');f.db.prepare("INSERT INTO organizations VALUES ('other','Other')").run();f.db.prepare("INSERT INTO users (id,org_id,email,name,role,password_hash) VALUES ('other','other','other@test','Other','BILLER','x')").run();assert.throws(()=>coverageView(f.db,{id:'other',org_id:'other'},context),/Encounter not found/);assert.throws(()=>recordCoverage(f.db,f.doctor,{...context,evidence}),/Access denied/);assert.throws(()=>coverageView(f.db,f.patient,context),/Access denied/)});
test('plan criteria never become member coverage; stale evidence and later unknown review supersede prior positive record',t=>{const f=fixture(t);assert.throws(()=>recordCoverage(f.db,f.biller,{...context,evidence:{...evidence,source_kind:'PLAN_DOCUMENT'}}),/cannot confirm/);recordCoverage(f.db,f.biller,{...context,evidence:{...evidence,source_kind:'PLAN_DOCUMENT',status:'CONDITIONAL'}});assert.equal(coverageView(f.db,f.biller,context).status,'POLICY_ONLY');recordCoverage(f.db,f.biller,{...context,evidence:{...evidence,checked_on:'2026-10-01',expires_on:'2026-10-02'}});assert.equal(coverageView(f.db,f.biller,context).status,'NOT_VERIFIED');assert.equal(coverageView(f.db,f.biller,context).stale,true);recordCoverage(f.db,f.biller,{...context,evidence});recordCoverage(f.db,f.biller,{...context,evidence:{...evidence,status:'UNKNOWN'}});assert.equal(coverageView(f.db,f.biller,context).status,'UNKNOWN');assert.throws(()=>recordCoverage(f.db,f.biller,{...context,evidence:{...evidence,reviewed:false}}),/review confirmation/)});
test('CPT imports require active admin authorization, license attestation, nonoverlapping dates and organization isolation',t=>{const f=fixture(t);f.db.prepare("UPDATE users SET role='ADMIN' WHERE id='biller-001'").run();const payload={license_attested:true,license_reference:'TEST ONLY - no real license',source_reference:'Synthetic test data, not CPT descriptors',codes:[{code:'00000',description:'SYNTHETIC TEST ONLY',starts_on:'2026-01-01',ends_on:'2026-12-31'}]};assert.throws(()=>importLicensedCodes(f.db,f.doctor,payload),/Access denied/);assert.throws(()=>importLicensedCodes(f.db,f.biller,{...payload,license_attested:false}),/authorization/);assert.equal(importLicensedCodes(f.db,f.biller,payload).imported,1);assert.throws(()=>importLicensedCodes(f.db,f.biller,payload),/Overlapping/);assert.equal(searchCodes(f.db,f.biller,{system:'CPT',q:'00000',service_date:'2026-10-09'}).total,1);f.db.prepare("INSERT INTO organizations VALUES ('other','Other')").run();f.db.prepare("INSERT INTO users (id,org_id,email,name,role,password_hash) VALUES ('other','other','other@test','Other','BILLER','x')").run();assert.equal(searchCodes(f.db,{id:'other',org_id:'other'},{system:'CPT',service_date:'2026-10-09'}).total,0);f.db.prepare("UPDATE users SET active=0 WHERE id='biller-001'").run();assert.throws(()=>importLicensedCodes(f.db,f.biller,payload),/Access denied/)});
