import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
function demo(){const actions=['assessment','plan','sign','checkin','roomed','seen','generatePlan','reviewGeneratedPlan'];const nodes=actions.map(action=>({dataset:{action}}));const activityNodes=['Review care plan','Discuss injection'].map(activity=>({dataset:{activity}}));const app={innerHTML:''},role={};const document={querySelector:q=>q==='#app'?app:q==='#role'?role:null,querySelectorAll:q=>q==='[data-action]'?nodes:q==='[data-activity]'?activityNodes:[]};const context=vm.createContext({document,structuredClone,Date,URL,window:{addEventListener(){}}});vm.runInContext(readFileSync(new URL('../demo/app.js',import.meta.url),'utf8').replace(/^import[^\n]*\n/,'')+'\nglobalThis.demoState=state;',context);return {toggle:a=>activityNodes.find(n=>n.dataset.activity===a).onclick(),state:context.demoState,act:a=>nodes.find(n=>n.dataset.action===a).onclick()};}
test('visit plan and signing wait for check-in, rooming and provider assessment',()=>{const d=demo();for(const a of ['seen','assessment','plan','sign'])d.act(a);assert.equal(d.state.plan,false);assert.equal(d.state.signed,false);d.act('checkin');d.act('roomed');d.act('plan');assert.equal(d.state.plan,false);d.act('seen');d.act('plan');assert.equal(d.state.plan,false);d.act('assessment');d.act('plan');d.act('sign');assert.equal(d.state.signed,true);});
test('MA checks in and rooms patient but cannot assess, plan or sign; patient and biller cannot record arrival',()=>{const d=demo();for(const role of ['PATIENT','BILLER']){d.state.role=role;d.act('checkin');assert.equal(d.state.checkinAt,'');}d.state.role='MA';d.act('checkin');d.act('roomed');for(const a of ['seen','assessment','plan','sign'])d.act(a);assert.ok(d.state.checkinAt);assert.ok(d.state.roomedAt);assert.equal(d.state.seenAt,'');assert.equal(d.state.plan,false);d.state.role='PHYSICIAN';d.act('seen');d.act('assessment');d.act('plan');d.state.role='MA';d.act('sign');assert.equal(d.state.signed,false);});

test('assessment-derived sample plan stays unsigned and needs clinician review',()=>{const d=demo();d.state.dictationAssessment='Fictional assessment for physician review.';d.act('generatePlan');assert.equal(d.state.generatedPlan,'');d.act('checkin');d.act('roomed');d.act('seen');d.act('generatePlan');assert.ok(d.state.generatedPlan);assert.equal(d.state.plan,false);assert.equal(d.state.signed,false);d.state.role='MA';d.act('reviewGeneratedPlan');assert.equal(d.state.planDraftReviewed,false);d.state.role='PHYSICIAN';d.state.dictationAssessment='Changed assessment';d.act('reviewGeneratedPlan');assert.equal(d.state.planDraftReviewed,false);d.state.dictationAssessment=d.state.planSource;d.act('reviewGeneratedPlan');assert.equal(d.state.planDraftReviewed,true);assert.equal(d.state.dictationPlan,d.state.generatedPlan);assert.equal(d.state.signed,false);});

test('visit activities support independent multiple selections',()=>{const d=demo();d.toggle('Review care plan');d.toggle('Discuss injection');assert.equal(d.state.visitActivities.length,2);d.toggle('Review care plan');assert.equal(d.state.visitActivities.join(),'Discuss injection');assert.equal(d.state.plan,false);});
