const app=document.querySelector('#app');
const state={role:'PHYSICIAN',page:'Today',assessment:false,plan:false,signed:false,checkedOut:false,denied:false,appealed:false};
const patient='Jordan Sample',payer='Example Health Plan';
function item(label,value){return `<div class="item row"><b>${label}</b><span>${value}</span></div>`}
function render(){const staff=state.role!=='PATIENT',pages=staff?['Today','Patients','Schedule','Inbox','Billing']:['Today','My care','Billing'];const nav=pages.map(p=>`<button class="nav ${state.page===p?'active':''}" data-page="${p}">${p}</button>`).join('');let content='';
  if(state.page==='Today')content=`<div class="grid"><div class="card"><h2>${staff?'Today’s practice':'Your care'}</h2><div class="stat">${staff?'1 appointment':'1 visit'}</div><p class="muted">Fictional example for a product walkthrough.</p></div><div class="card"><h2>Next appointment</h2>${item(patient,'Tomorrow · 10:00 AM')}${item('Status','Scheduled')}</div>${staff?`<div class="card"><h2>Work queue</h2>${item('Callback','Confirm follow-up')}${item('Claim',state.checkedOut?'Awaiting connector':'Not checked out')}</div>`:''}</div>`;
  if(state.page==='Schedule')content=`<div class="card"><h2>Schedule</h2>${item(patient,'Tomorrow · 10:00 AM')}${item('Visit','Follow-up')}</div>`;
  if(state.page==='Inbox')content=`<div class="card"><h2>Inbox and tasks</h2>${item('Callback','Confirm follow-up appointment')}${item('Message','No unread messages')}</div>`;
  if(state.page==='Patients'||state.page==='My care')content=`<div class="grid"><div class="card"><h2>${staff?'Patient chart':'My chart'}</h2>${item('Patient',patient)}${item('Coverage',payer)}${item('Encounter',state.checkedOut?'Checked out':state.signed?'Signed':'Open')}<p class="muted">Symptoms, medications, labs, images, consents, calls and billing attach to this chart in the working foundation.</p></div><div class="card"><h2>Structured visit note</h2>${item('Assessment',state.assessment?'Recorded':'Missing')}${item('Plan',state.plan?'Recorded':'Missing')}${state.role==='PHYSICIAN'&&!state.signed?`<div class="row"><button data-action="assessment">Add assessment</button><button data-action="plan">Add plan</button><button data-action="sign" ${!state.assessment||!state.plan?'disabled':''}>Sign encounter</button></div>`:''}${state.signed?'<p class="notice">Signed by the fictional physician.</p>':''}</div></div>${state.role==='PHYSICIAN'&&state.signed&&!state.checkedOut?`<div class="card"><h2>Billing at checkout</h2>${item('Coding','Procedure, diagnosis and modifier review')}${item('Documentation check','Assessment and plan present')}${item('Authorization','Match payer, patient, procedure and date when required')}<button data-action="checkout">Validate and check out</button></div>`:''}`;
  if(state.page==='Billing')content=`<div class="grid"><div class="card"><h2>${staff?'Claim worklist':'Your claim'}</h2>${item('Payer',payer)}${item('Charge',state.checkedOut?'$150.00':'Pending checkout')}${item('Status',state.denied?'Demo denial recorded':state.checkedOut?'Awaiting connector · not sent':'No claim yet')}<p class="notice">The demo never sends a claim or data to an insurer.</p></div><div class="card"><h2>Claim timeline</h2>${item('Signed encounter',state.signed?'Complete':'Pending')}${item('Checkout',state.checkedOut?'Validated; claim queued':'Pending')}${item('Payer response','No live connection')}${state.role==='BILLER'&&state.checkedOut?`<button data-action="deny" ${state.denied?'disabled':''}>Simulate denial</button> ${state.denied?`<button data-action="appeal" ${state.appealed?'disabled':''}>Draft appeal</button>`:''}`:''}${state.appealed?'<p class="notice">Demo appeal draft created for review.</p>':''}</div></div>`;
  app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">Front Desk Mate<br><small>Interactive walkthrough</small></div><nav>${nav}</nav></aside><main class="main"><header><div><h1>${state.page}</h1><small>Fictional ${state.role.toLowerCase()} view</small></div><label>View as<select id="role"><option value="PHYSICIAN" ${state.role==='PHYSICIAN'?'selected':''}>Physician</option><option value="BILLER" ${state.role==='BILLER'?'selected':''}>Billing</option><option value="PATIENT" ${state.role==='PATIENT'?'selected':''}>Patient</option></select></label></header><div class="notice"><b>Interactive concept demo · fictional data only.</b> This page stores nothing and accepts no patient data. The actual application is still in development.</div>${content}<div class="card"><h2>Next stage</h2><p>Production will need individual accounts, secure records, qualified coding review, payer integrations, signed vendor agreements, and security validation before real patient use.</p></div></main></div>`;
  document.querySelector('#role').onchange=e=>{state.role=e.target.value;state.page='Today';render()};document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='assessment')state.assessment=true;if(a==='plan')state.plan=true;if(a==='sign')state.signed=true;if(a==='checkout')state.checkedOut=true;if(a==='deny')state.denied=true;if(a==='appeal')state.appealed=true;render()});
}
render();
