import { normalizeToxin, toxinAssessment, toxinLineError, TOXIN_PRODUCTS } from './botulinum.js';
import { uid, now, audit } from './db.js';
import { searchCodes } from './code-coverage.js';
const fail=(status,message)=>Object.assign(Error(message),{status});
export const SERVICE_TYPES=['BOTULINUM_TOXIN','CT','XRAY','MRI','ULTRASOUND','LAB','INJECTION','MEDICATION','EVALUATION','THERAPY','PROCEDURE','OTHER'];
const STATES=['DISCUSSED','ORDERED','PERFORMED_IN_HOUSE','PERFORMED_ELSEWHERE','CANCELED'];
// Phrase detection only: negation, intent, clinical need and performance are never inferred.
export function noteServiceMentions(sections){
 const patterns=[['BOTULINUM_TOXIN',/\b(?:botox|botulinum toxin|dysport|myobloc|xeomin|daxxify)\b/gi],['CT',/\b(?:CT(?:\s+scan)?|computed tomography)\b/gi],['XRAY',/\b(?:x[ -]?rays?|radiograph(?:y|s)?)\b/gi],['MRI',/\b(?:MRI|magnetic resonance imaging)\b/gi],['ULTRASOUND',/\b(?:ultrasound|sonograph(?:y|ic))\b/gi],['LAB',/\b(?:laboratory|blood ?work|CBC|urinalysis)\b/gi],['INJECTION',/\binjections?\b/gi],['THERAPY',/\b(?:physical therapy|occupational therapy)\b/gi],['PROCEDURE',/\b(?:surgery|ablation|spinal cord stimulator|pain pump)\b/gi]];
 return sections.flatMap(section=>patterns.flatMap(([category,pattern])=>Array.from(section.content.matchAll(pattern),match=>({source_section_id:section.id,source_kind:section.kind,category,matched_phrase:match[0],start_offset:match.index,end_offset:match.index+match[0].length,excerpt:section.content.slice(Math.max(0,match.index-90),Math.min(section.content.length,match.index+match[0].length+140)),status:'MENTION_ONLY',notice:'Phrase mention only: may be historical, negated, discussed, ordered or performed. Clinician must clarify.'})))).slice(0,100);
}
export function migrateAppointmentCoding(db){db.exec(`
 CREATE TABLE IF NOT EXISTS encounter_services (id TEXT PRIMARY KEY,org_id TEXT NOT NULL REFERENCES organizations(id),encounter_id TEXT NOT NULL REFERENCES encounters(id),source_section_id TEXT NOT NULL REFERENCES clinical_sections(id),supersedes_id TEXT UNIQUE REFERENCES encounter_services(id),category TEXT NOT NULL,state TEXT NOT NULL,details_json TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL);
 CREATE INDEX IF NOT EXISTS encounter_service_scope ON encounter_services(org_id,encounter_id);
 CREATE TABLE IF NOT EXISTS service_code_reviews (id TEXT PRIMARY KEY,org_id TEXT NOT NULL REFERENCES organizations(id),encounter_id TEXT NOT NULL REFERENCES encounters(id),service_id TEXT NOT NULL REFERENCES encounter_services(id),line_json TEXT NOT NULL,catalog_json TEXT NOT NULL,rationale TEXT NOT NULL,reviewed_by TEXT NOT NULL REFERENCES users(id),reviewed_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS claim_line_sources (claim_line_id TEXT PRIMARY KEY REFERENCES claim_lines(id),review_id TEXT NOT NULL UNIQUE REFERENCES service_code_reviews(id));
 CREATE TRIGGER IF NOT EXISTS services_no_update BEFORE UPDATE ON encounter_services BEGIN SELECT RAISE(ABORT,'Service records are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS services_no_delete BEFORE DELETE ON encounter_services BEGIN SELECT RAISE(ABORT,'Service records are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS code_reviews_no_update BEFORE UPDATE ON service_code_reviews BEGIN SELECT RAISE(ABORT,'Code reviews are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS code_reviews_no_delete BEFORE DELETE ON service_code_reviews BEGIN SELECT RAISE(ABORT,'Code reviews are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS claim_sources_no_update BEFORE UPDATE ON claim_line_sources BEGIN SELECT RAISE(ABORT,'Claim source links are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS claim_sources_no_delete BEFORE DELETE ON claim_line_sources BEGIN SELECT RAISE(ABORT,'Claim source links are immutable'); END;
 `)}
function access(db,user,id){const u=db.prepare('SELECT * FROM users WHERE id=? AND org_id=? AND active=1').get(user.id,user.org_id);if(!u||!['PHYSICIAN','BILLER','ADMIN'].includes(u.role))throw fail(403,'Practice coding staff required');const e=db.prepare('SELECT * FROM encounters WHERE id=? AND org_id=?').get(id,u.org_id);if(!e)throw fail(404,'Encounter not found');return {u,e}}
function text(v,name,max=1000,optional=false){if(optional&&(v===undefined||v===''))return '';if(typeof v!=='string'||!v.trim()||v.length>max)throw fail(400,`Invalid ${name}`);return v.trim()}
function latest(db,id,org,encounter){return db.prepare('SELECT s.* FROM encounter_services s WHERE s.id=? AND s.org_id=? AND s.encounter_id=? AND NOT EXISTS(SELECT 1 FROM encounter_services n WHERE n.supersedes_id=s.id)').get(id,org,encounter)}
export function serviceGaps(service){const d=typeof service.details_json==='string'?JSON.parse(service.details_json):service.details;const gaps=[];
 if(!d.indication)gaps.push('Documented indication or reason for service');
 if(['CT','XRAY','MRI','ULTRASOUND','INJECTION','PROCEDURE'].includes(service.category)&&!d.body_part)gaps.push('Body region / procedure site');
 if(['CT','XRAY','MRI','ULTRASOUND','INJECTION','PROCEDURE'].includes(service.category)&&!d.laterality)gaps.push('Laterality or documented not applicable');
 if(['CT','MRI'].includes(service.category)&&!['NONE','WITH','WITHOUT_AND_WITH'].includes(d.contrast))gaps.push('Contrast protocol');
 if(service.category==='XRAY'&&!Number.isSafeInteger(d.views))gaps.push('Number of X-ray views');
 if(['INJECTION','MEDICATION'].includes(service.category)){if(!d.drug)gaps.push('Drug / formulation');if(!d.dose)gaps.push('Administered dose and measurement unit');if(!d.route)gaps.push('Administration route')}
 if(['LAB','ULTRASOUND','EVALUATION','THERAPY','PROCEDURE','OTHER'].includes(service.category)&&!d.method)gaps.push('Specific service / technique / assessment details');
 if(service.state==='PERFORMED_IN_HOUSE'&&!d.performance_reference)gaps.push('Performed-service report or administration reference');
 if(service.category==='BOTULINUM_TOXIN'){if(!d.route)gaps.push('Administration route');if(!d.method)gaps.push('Documented injection/procedure technique');if(!d.toxin)gaps.push('Detailed toxin administration record');else gaps.push(...toxinAssessment(d.toxin,service.service_date||'').gaps)}
 return gaps;
}
export function recordService(db,user,id,b){const {u,e}=access(db,user,id);if(u.id!==e.clinician_id||u.role!=='PHYSICIAN'||e.status!=='OPEN')throw fail(403,'Assigned clinician must record services before signing');
 if(!b||b.reviewed!==true||!SERVICE_TYPES.includes(b.category)||!STATES.includes(b.state))throw fail(400,'Confirm reviewed service facts, category and status');
 const source=db.prepare('SELECT * FROM clinical_sections WHERE id=? AND encounter_id=?').get(b.source_section_id,e.id);if(!source)throw fail(400,'Select a source note from this encounter');
 const details={description:text(b.description,'service description',500),indication:text(b.indication,'indication',1000,true),body_part:text(b.body_part,'body region',200,true),laterality:text(b.laterality,'laterality',100,true),contrast:text(b.contrast,'contrast',50,true),views:b.views==null||b.views===''?null:b.views,drug:text(b.drug,'drug/formulation',200,true),dose:text(b.dose,'dose',200,true),route:text(b.route,'route',100,true),method:text(b.method,'technique/service details',1000,true),performance_reference:text(b.performance_reference,'performance report reference',1000,true),search_terms:text(b.search_terms,'catalog search terms',120,true),...(b.category==='BOTULINUM_TOXIN'?{toxin:normalizeToxin(b.toxin)}:{})};
 if(details.views!==null&&(!Number.isSafeInteger(details.views)||details.views<1||details.views>100))throw fail(400,'Invalid X-ray view count');
 if(details.contrast&&!['UNKNOWN','NONE','WITH','WITHOUT_AND_WITH'].includes(details.contrast))throw fail(400,'Invalid contrast protocol');
 const parent=b.supersedes_id||null,idNew=uid();db.exec('BEGIN IMMEDIATE');try{const existing=db.prepare('SELECT s.id FROM encounter_services s WHERE s.org_id=? AND s.encounter_id=? AND s.source_section_id=? AND s.supersedes_id IS ? AND s.category=? AND s.state=? AND s.details_json=? AND NOT EXISTS(SELECT 1 FROM encounter_services r WHERE r.supersedes_id=s.id)').get(u.org_id,e.id,source.id,parent,b.category,b.state,JSON.stringify(details));if(existing){db.exec('COMMIT');return {id:existing.id,duplicate:true,gaps:serviceGaps({category:b.category,state:b.state,details,service_date:e.date_of_service})}}if(parent&&!latest(db,parent,u.org_id,e.id))throw fail(409,'Service revision is stale or outside this encounter');db.prepare('INSERT INTO encounter_services VALUES (?,?,?,?,?,?,?,?,?,?)').run(idNew,u.org_id,e.id,source.id,parent,b.category,b.state,JSON.stringify(details),u.id,now());audit(db,u,parent?'REVISE_SERVICE':'RECORD_SERVICE','encounter_service',idNew);db.exec('COMMIT')}catch(err){db.exec('ROLLBACK');throw err}return {id:idNew,gaps:serviceGaps({category:b.category,state:b.state,details,service_date:e.date_of_service})};
}
export function appointmentCoding(db,user,id){const {u,e}=access(db,user,id);const services=db.prepare('SELECT s.*,n.content AS source_text,n.kind AS source_kind FROM encounter_services s JOIN clinical_sections n ON n.id=s.source_section_id WHERE s.org_id=? AND s.encounter_id=? AND NOT EXISTS(SELECT 1 FROM encounter_services r WHERE r.supersedes_id=s.id) ORDER BY s.created_at,s.rowid').all(u.org_id,e.id).map(s=>{const details=JSON.parse(s.details_json),gaps=serviceGaps({...s,service_date:e.date_of_service}),billable=s.state==='PERFORMED_IN_HOUSE'&&!gaps.length;const term=details.toxin?.product?.hcpcs_code||details.search_terms;const search=term?searchCodes(db,u,{system:['BOTULINUM_TOXIN','MEDICATION','INJECTION'].includes(s.category)?'HCPCS':'CPT',q:term,service_date:e.date_of_service}):null;
 return {...s,details,...(details.toxin?{toxin_summary:toxinAssessment(details.toxin,e.date_of_service)}:{}),gaps,billing_review_allowed:billable,catalog_candidates:search?.results||[],catalog_available:search?.available||false,catalog_system:search?.system||(['BOTULINUM_TOXIN','MEDICATION','INJECTION'].includes(s.category)?'HCPCS':'CPT'),candidate_notice:'Description matches for professional review only. Not an automatic clinical/coding recommendation. No validated diagnosis-to-procedure rule or coverage conclusion is inferred.'}});
 const sections=db.prepare('SELECT id,kind,content FROM clinical_sections WHERE encounter_id=? ORDER BY created_at,id').all(e.id),mentions=noteServiceMentions(sections);
 const reviews=db.prepare('SELECT * FROM service_code_reviews WHERE org_id=? AND encounter_id=? ORDER BY rowid DESC').all(u.org_id,e.id).map(r=>({...r,line:JSON.parse(r.line_json),catalog:JSON.parse(r.catalog_json),current:services.some(s=>s.id===r.service_id)}));audit(db,u,'VIEW_APPOINTMENT_CODING','encounter',e.id);return {encounter:e,services,reviews,mentions,notice:'Service facts are clinician-entered and linked to source notes. Phrase mentions are highlighted for clarification; no AI transcription, clinical interpretation or automatic code assignment is connected. Ordered, discussed, external or canceled services cannot become this clinic’s performed-service claim lines.'};
}
export function reviewServiceCode(db,user,id,b){const {u,e}=access(db,user,id);if(!['SIGNED','CHECKED_OUT'].includes(e.status))throw fail(409,'Sign the clinical record before final coding review');if(u.role==='PHYSICIAN'&&u.id!==e.clinician_id)throw fail(403,'Assigned clinician or billing staff must review');if(!b||b.reviewed!==true)throw fail(400,'Coding review confirmation required');
 const s=latest(db,b.service_id,u.org_id,e.id);if(!s)throw fail(404,'Current service not found');if(s.state!=='PERFORMED_IN_HOUSE'||serviceGaps({...s,service_date:e.date_of_service}).length)throw fail(422,'Only documented in-house performed services with completed details can receive a billing code review');
 const system=b.procedure_system;if(!['HCPCS','CPT'].includes(system))throw fail(400,'Unsupported procedure system');
 const procedure=text(b.procedure_code,'procedure code',7).toUpperCase(),diagnosis=text(b.diagnosis_code,'documented diagnosis code',8).toUpperCase(),modifier=text(b.modifier,'modifier',20,true).toUpperCase();
 if(!Number.isSafeInteger(b.units)||b.units<1||b.units>100000||!/^([A-Z0-9]{2}(,[A-Z0-9]{2})*)?$/.test(modifier))throw fail(400,'Review coding units/modifier');
 const procedureSearch=searchCodes(db,u,{system,q:procedure,service_date:e.date_of_service}),code=procedureSearch.results.find(r=>r.code===procedure),dx=searchCodes(db,u,{system:'ICD10CM',q:diagnosis,service_date:e.date_of_service}).results.find(r=>r.code===diagnosis);if(!code||!dx)throw fail(422,'Procedure and diagnosis must exist in installed, date-valid catalogs. Licensed CPT import may be needed.');
 const details=JSON.parse(s.details_json),toxinCode=Object.values(TOXIN_PRODUCTS).some(p=>p.hcpcs_code===procedure);
 let toxinPolicy=null;
 if(system==='HCPCS'&&toxinCode){if(!details.toxin)throw fail(422,'A detailed botulinum-toxin administration record is required for this drug code');const reviewedToxin=normalizeToxin({...details.toxin,waste_policy:b.waste_policy,waste_policy_reference:b.waste_policy_reference});toxinPolicy={waste_policy:reviewedToxin.waste_policy,waste_policy_reference:reviewedToxin.waste_policy_reference};const error=toxinLineError(reviewedToxin,toxinAssessment(reviewedToxin,e.date_of_service),{...b,procedure_code:procedure,modifier});if(error)throw fail(422,error)}
 const rationale=text(b.rationale,'documentation and coding rationale',2000),line={procedure_system:system,procedure_code:procedure,diagnosis_code:diagnosis,modifier,units:b.units,...(toxinCode&&system==='HCPCS'?{drug_component:b.drug_component}:{})},catalog={procedure:code,diagnosis:dx,release:procedureSearch.source,service_date:e.date_of_service,...(toxinPolicy?{toxin_policy:toxinPolicy}:{})},reviewId=uid();
 db.exec('BEGIN IMMEDIATE');try{db.prepare('INSERT INTO service_code_reviews VALUES (?,?,?,?,?,?,?,?,?)').run(reviewId,u.org_id,e.id,s.id,JSON.stringify(line),JSON.stringify(catalog),rationale,u.id,now());audit(db,u,'REVIEW_SERVICE_CODE','service_code_review',reviewId);db.exec('COMMIT')}catch(err){db.exec('ROLLBACK');throw err}return {id:reviewId,line:{...line,source_review_id:reviewId},notice:'Human-reviewed code; coverage and payment remain separate checks.'};
}
export function sourceLineIssues(db,e,line){if(Object.values(TOXIN_PRODUCTS).some(p=>p.hcpcs_code===line.procedure_code)&&!line.source_review_id)return ['Botulinum-toxin drug billing requires a detailed source-linked administration review.'];const hasServices=db.prepare('SELECT 1 FROM encounter_services WHERE encounter_id=? AND org_id=?').get(e.id,e.org_id);if(!hasServices&&!line.source_review_id)return [];
 if(typeof line.source_review_id!=='string')return ['Each claim line needs a source-linked performed-service code review.'];
 const r=db.prepare('SELECT * FROM service_code_reviews WHERE id=? AND org_id=? AND encounter_id=?').get(line.source_review_id,e.org_id,e.id);if(!r)return ['Invalid or cross-encounter service code review.'];const s=latest(db,r.service_id,e.org_id,e.id),reviewed=JSON.parse(r.line_json);
 if(!s||s.state!=='PERFORMED_IN_HOUSE'||serviceGaps({...s,service_date:e.date_of_service}).length)return ['Source service is not a current documented in-house performed service.'];
 if(Object.keys(reviewed).some(k=>(line[k]||(k==='procedure_system'?'CPT':k==='modifier'?'':''))!==reviewed[k]))return ['Claim values differ from the reviewed service code, diagnosis, units or modifier.'];
 return [];
}
